apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvClusterSecurityRule
  metadata:
    creationTimestamp: null
    name: external
  spec:
    egress: []
    file: []
    ingress: []
    process: []
    response: null
    target:
      policymode: N/A
      selector:
        comment: ""
        name: external
        original_name: ""
kind: List
metadata: {}
