apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvClusterSecurityRule
  metadata:
    creationTimestamp: null
    name: nv.iperfserver
  spec:
    dlp:
      settings: []
      status: true
    egress:
    - action: deny
      applications:
      - any
      name: external-egress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        name: external
        original_name: ""
    - action: deny
      applications:
      - any
      name: containers-egress-1
      ports: tcp/6068
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: container
          op: =
          value: '*'
        name: containers
        original_name: ""
    file: []
    ingress:
    - action: allow
      applications:
      - any
      name: nv.iperfserver-ingress-0
      ports: tcp/6068
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: container
          op: =
          value: '*'
        name: containers
        original_name: ""
    process:
    - action: allow
      allow_update: false
      name: iperf
      path: /usr/bin/iperf
    process_profile:
      baseline: zero-drift
      mode: Discover
    response: null
    target:
      policymode: Discover
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: iperfserver
        grp_band_width: 0
        grp_sess_cur: 0
        grp_sess_rate: 0
        mon_metric: false
        name: nv.iperfserver
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: {}
