apiVersion: neuvector.com/v1
kind: NvConfigSecurityRule
metadata:
  creationTimestamp: null
  name: fed
spec:
  fed_config:
    name: fed
    webhooks:
    - enable: true
      name: fed.webhook1
      type: JSON
      url: https://test123.com
      use_proxy: false
    - enable: true
      name: fed.webhook2
      type: JSON
      url: https://test345.com
      use_proxy: false
    - enable: true
      name: fed.webhook3
      type: JSON
      url: https://test789.com
      use_proxy: false
