apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvClusterSecurityRule
  metadata:
    creationTimestamp: null
    name: fed.iperfserver
  spec:
    dlp:
      settings: []
      status: true
    egress: []
    file: []
    ingress: []
    process: []
    response: null
    target:
      policymode: N/A
      selector:
        comment: ""
        criteria:
        - key: image
          op: =
          value: nginx
        grp_band_width: 0
        grp_sess_cur: 0
        grp_sess_rate: 0
        mon_metric: false
        name: fed.iperfserver
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: {}
