apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvClusterSecurityRule
  metadata:
    creationTimestamp: null
    name: fed.g1
  spec:
    dlp:
      settings: []
      status: true
    egress:
    - action: deny
      applications:
      - any
      name: external-egress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        name: external
        original_name: ""
    file:
    - app: []
      behavior: monitor_change
      filter: /tmp/*
      recursive: false
    ingress: []
    process:
    - action: allow
      allow_update: false
      name: '*'
      path: /usr/bin/ls
    response:
    - actions:
      - suppress-log
      conditions:
      - type: level
        value: Error
      event: security-event
      policy_name: fed
    target:
      policymode: N/A
      selector:
        comment: ""
        criteria:
        - key: container
          op: =
          value: myServer
        grp_band_width: 0
        grp_sess_cur: 0
        grp_sess_rate: 0
        mon_metric: false
        name: fed.g1
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: {}
