apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvResponseRuleSecurityRule
  metadata:
    creationTimestamp: null
    name: fed.security-event--59cd257f0974272c1002e6e67792c2a6afc5155ddfdf7da52231e277d827f87b
  spec:
    rule:
      actions:
      - suppress-log
      conditions:
      - type: level
        value: Error
      event: security-event
      policy_name: fed
kind: List
metadata: {}
