apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    creationTimestamp: null
    name: nv.cert-manager.cert-manager
    namespace: cert-manager
  spec:
    dlp:
      settings: []
      status: true
    egress: []
    file: []
    ingress:
    - action: allow
      applications:
      - HTTP
      name: nv.cert-manager.cert-manager-ingress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        name: Workload:ingress
        original_name: ""
    process:
    - action: allow
      allow_update: false
      name: controller
      path: /app/cmd/controller/controller
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    process_profile:
      baseline: zero-drift
      mode: Discover
    response: null
    target:
      policymode: Discover
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: cert-manager.cert-manager
        - key: domain
          op: =
          value: cert-manager
        grp_band_width: 0
        grp_sess_cur: 0
        grp_sess_rate: 0
        mon_metric: false
        name: nv.cert-manager.cert-manager
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: {}
