apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvClusterSecurityRule
  metadata:
    creationTimestamp: null
    name: fed.test
  spec:
    dlp:
      settings: []
      status: true
    egress:
    - action: allow
      applications:
      - any
      name: fed.nodes-egress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        name: fed.nodes
        original_name: ""
    - action: deny
      applications:
      - any
      name: external-egress-1
      ports: any
      priority: 0
      selector:
        comment: ""
        name: external
        original_name: ""
    file: []
    ingress: []
    process: []
    response: null
    target:
      policymode: N/A
      selector:
        comment: ""
        criteria:
        - key: container
          op: =
          value: myServer
        - key: image
          op: =
          value: '*nginx*'
        grp_band_width: 0
        grp_sess_cur: 0
        grp_sess_rate: 0
        mon_metric: false
        name: fed.test
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: {}
