apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    creationTimestamp: null
    name: nv.cilium-operator.kube-system
    namespace: kube-system
  spec:
    dlp:
      settings: []
      status: true
    egress: []
    file: []
    ingress:
    - action: allow
      applications:
      - any
      name: nv.cilium-operator.kube-system-ingress-0
      ports: tcp/9234
      priority: 0
      selector:
        comment: ""
        name: nodes
        original_name: ""
    process:
    - action: allow
      allow_update: false
      name: cilium-operator-generic
      path: /usr/bin/cilium-operator-generic
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    process_profile:
      baseline: zero-drift
      mode: Discover
    response: null
    target:
      policymode: Discover
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: cilium-operator.kube-system
        - key: domain
          op: =
          value: kube-system
        grp_band_width: 0
        grp_sess_cur: 0
        grp_sess_rate: 0
        mon_metric: false
        name: nv.cilium-operator.kube-system
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: {}
