apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvResponseRuleSecurityRule
  metadata:
    name: security-event--8719871d2f07fd9a674f3c78675b1fdae707f0bde044e8d4276d487bab6545a4
  spec:
    rule:
      actions:
      - webhook
      conditions:
      - type: level
        value: Error
      disable: true
      event: security-event
      policy_name: default
- apiVersion: neuvector.com/v1
  kind: NvResponseRuleSecurityRule
  metadata:
    name: security-event--4c16d59acac6f13795eec42f538c7da2c2a041076e8ccf4f4e92d95e38596d41
  spec:
    rule:
      actions:
      - webhook
      disable: true
      event: security-event
      policy_name: default
kind: List
metadata: {}
