apiVersion: neuvector.com/v1
items:
- apiVersion: neuvector.com/v1
  kind: NvVulnerabilityProfile
  metadata:
    name: default
  spec:
    profile:
      entries:
      - comment: ""
        days: 0
        domains: []
        images:
        - nginx:1.23
        name: CVE-2021-4534
kind: List
metadata: {}
