apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvWafSecurityRule
  metadata:
    name: sensor.spring4shell
  spec:
    sensor:
      comment: Spring4Shell - 0day RCE Vulnerability found in Java Spring Framework
      name: sensor.spring4shell
      rules:
      - name: rule.spring4shell
        patterns:
        - context: body
          key: pattern
          op: regex
          value: if.*equals.*request\.getParameter.*pwd.*getRuntime.*exec.*request\.getParameter.*cmd.*getInputStream.*read.*print.*classLoader
- apiVersion: neuvector.com/v1
  kind: NvWafSecurityRule
  metadata:
    name: waf
  spec:
    sensor:
      comment: ""
      name: waf
      rules:
      - name: r1
        patterns:
        - context: packet
          key: pattern
          op: regex
          value: \b4(\d{3})(?!\1{3})([ -]?)(?!(\d)\3{3})(\d{4})\2(?!\4|(\d)\5{3}|1234|2345|3456|5678|7890)(\d{4})\2(?!\6|(\d)\7{3}|1234|3456)\d{4}\b
kind: List
metadata: {}
