apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvWafSecurityRule
  metadata:
    creationTimestamp: null
    name: fed.sensor.spring4shell
  spec:
    sensor:
      comment: Spring4Shell - 0day RCE Vulnerability found in Java Spring Framework
      name: fed.sensor.spring4shell
      rules:
      - name: rule.spring4shell
        patterns:
        - context: body
          key: pattern
          op: regex
          value: if.*equals.*request\.getParameter.*pwd.*getRuntime.*exec.*request\.getParameter.*cmd.*getInputStream.*read.*print.*classLoader
- apiVersion: neuvector.com/v1
  kind: NvWafSecurityRule
  metadata:
    creationTimestamp: null
    name: fed.waf.s1
  spec:
    sensor:
      comment: waf sensor
      name: fed.waf.s1
      rules:
      - name: r1
        patterns:
        - context: packet
          key: pattern
          op: regex
          value: "234567"
- apiVersion: neuvector.com/v1
  kind: NvWafSecurityRule
  metadata:
    creationTimestamp: null
    name: fed.waf.s2
  spec:
    sensor:
      comment: ""
      name: fed.waf.s2
      rules:
      - name: r1
        patterns:
        - context: packet
          key: pattern
          op: regex
          value: dfdghjhj
kind: List
metadata: {}
