apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    creationTimestamp: null
    name: nv.iperfserver.neuvector-1
    namespace: neuvector-1
  spec:
    dlp:
      settings: []
      status: true
    egress:
    - action: deny
      applications:
      - any
      name: containers-egress-0
      ports: tcp/6068
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: container
          op: =
          value: '*'
        name: containers
        original_name: ""
    file: []
    ingress:
    - action: allow
      applications:
      - any
      name: nv.iperfserver.neuvector-1-ingress-0
      ports: tcp/6068
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: container
          op: =
          value: '*'
        name: containers
        original_name: ""
    process: []
    process_profile:
      baseline: zero-drift
      mode: Discover
    response: null
    target:
      policymode: Discover
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: iperfserver.neuvector-1
        - key: domain
          op: =
          value: neuvector-1
        grp_band_width: 0
        grp_sess_cur: 0
        grp_sess_rate: 0
        mon_metric: false
        name: nv.iperfserver.neuvector-1
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: {}
