apiVersion: neuvector.com/v1
items:
- apiVersion: neuvector.com/v1
  kind: NvVulnerabilityProfile
  metadata:
    creationTimestamp: null
    name: default
  spec:
    profile:
      entries:
      - comment: ""
        days: 0
        domains: []
        images: []
        name: CVE-2021-4534
kind: List
metadata: {}
